@API_ENDPOINT = {{$dotenv API_ENDPOINT}}
@ID_TOKEN = {{$dotenv ID_TOKEN}}

@PartitionType = Job
@PartitionId = 019491f6-4888-75ba-9816-7d8be3e16610
@SortType = Log
@SortId = 019491f6-70bb-7cdd-8b1c-27bc09720fe4

### DELETE /{PartitionType}/{PartitionId}/{SortType}/{SortId}

DELETE {{API_ENDPOINT}}/{{PartitionType}}/{{PartitionId}}/{{SortType}}/{{SortId}}
Authorization: Bearer {{ID_TOKEN}}

### GET /{PartitionType}/{PartitionId}/{SortType}

GET {{API_ENDPOINT}}/{{PartitionType}}/{{PartitionId}}/{{SortType}}
Authorization: Bearer {{ID_TOKEN}}

### GET /{PartitionType}/{PartitionId}/{SortType}/{SortId}

GET {{API_ENDPOINT}}/{{PartitionType}}/{{PartitionId}}/{{SortType}}/{{SortId}}
Authorization: Bearer {{ID_TOKEN}}

### GET /{SortType}

GET {{API_ENDPOINT}}/{{SortType}}
Authorization: Bearer {{ID_TOKEN}}

### PUT /{PartitionType}/{PartitionId}/{SortType}/{SortId}

PUT {{API_ENDPOINT}}/{{PartitionType}}/{{PartitionId}}/{{SortType}}/{{SortId}}
Authorization: Bearer {{ID_TOKEN}}

{
	"personId": "019491b4-4d1f-7df2-be95-62e0e684353f",
	"hours": 1.25
}
