@API_ENDPOINT = {{$dotenv API_ENDPOINT}}
@ID_TOKEN = {{$dotenv ID_TOKEN}}

@PartitionType = Person
@PartitionId = 01902e98-2fa0-7e52-a13b-7ac25c53ff00
@SortType = PersonMetadata

### DELETE /{PartitionType}/{PartitionId}/{SortType}

DELETE {{API_ENDPOINT}}/{{PartitionType}}/{{PartitionId}}/{{SortType}}
Authorization: Bearer {{ID_TOKEN}}

### GET /{PartitionType}/{PartitionId}/{SortType}

GET {{API_ENDPOINT}}/{{PartitionType}}/{{PartitionId}}/{{SortType}}
Authorization: Bearer {{ID_TOKEN}}

### GET /{SortType}

GET {{API_ENDPOINT}}/{{SortType}}
Authorization: Bearer {{ID_TOKEN}}

### PUT /{PartitionType}/{PartitionId}/{SortType}

PUT {{API_ENDPOINT}}/{{PartitionType}}/{{PartitionId}}/{{SortType}}
Authorization: Bearer {{ID_TOKEN}}

{
	"givenName": "Jose",
	"familyName": "Ramirez"
}
