name: "Deploy Environment Infrastructure"
on:
  push:
    branches: [prod, staging, dev]
    paths: [.github/workflows/deploy-infrastructure.yml, cmd/**, environments/**, internal/**, pkg/**]
permissions:
  contents: read
  id-token: write
jobs:
  deploy_environment_infrastructure:
    name: "Deploy Environment Infrastructure"
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'prod' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}
    defaults:
      run:
        shell: bash
        working-directory: environments/${{ github.ref_name }}/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Try this
        uses: actions/github-script@v7
        with:
          script: |
            console.log(process.env)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
      - name: Confirm Go version
        run: go version
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod tidy
      - name: Build Go functions
        working-directory: cmd/
        run: |
          for dir in *; do
            if [ -d $dir ]; then
              echo "Building $(basename $dir)..."
              GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o $dir/bootstrap $dir/main.go
              echo "Build complete for $(basename $dir)."
            fi
          done
      - name: Configure Git credentials
        run: git config --global url."https://${{ vars.TF_VAR_GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.TF_VAR_AWS_REGION }}
          role-to-assume: ${{ vars.TF_VAR_IAM_GITHUB_OIDC_ROLE_ARN }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Check Terraform format
        run: terraform fmt -check
      - name: Initialize Terraform
        run: terraform init -input=false
      - name: Apply Terraform infrastructure
        run: terraform apply -input=false -auto-approve
